# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
