# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_foodtype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.FoodType'),
            preserve_default=False,
        ),
    ]
