# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='foodtype',
        ),
    ]
