# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20171128_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
