# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20171125_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staple',
            name='food',
        ),
        migrations.DeleteModel(
            name='Staple',
        ),
    ]
