# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_remove_foodgrocerysection_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodgrocerysection',
            old_name='sectionName',
            new_name='section',
        ),
    ]
