# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20171128_0209'),
        ('grocery', '0007_auto_20180210_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypeDefaultSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodType')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.GrocerySection')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.GroceryStore')),
            ],
        ),
    ]
