# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_foodtypedefaultsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerysection',
            options={'ordering': ['store', 'order']},
        ),
        migrations.AlterField(
            model_name='foodtypedefaultsection',
            name='foodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultSection', to='food.FoodType'),
        ),
        migrations.AlterField(
            model_name='grocerysection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='grocery.GroceryStore'),
        ),
    ]
