# Generated by Django 2.1.5 on 2019-08-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_auto_20180227_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
