// actions.js
export const MATCH_GROCERY = 'MATCH_GROCERY';
export const CLEAR_MATCH_GROCERY = 'CLEAR_MATCH_GROCERY';
export const SET_FILTER = 'SET_FILTER';
export const SET_PREV_SEARCH = 'SET_PREV_SEARCH';

export const SET_FOODTYPE_CURRENT = 'SET_FOODTYPE_CURRENT';
export const GROCERY_POPULATE_ADDLIST = 'GROCERY_POPULATE_ADDLIST';
export const GROCERY_LIST_POPULATE = 'GROCERY_LIST_POPULATE';

export const SET_FOODTYPE_DEFAULT = 'SET_FOODTYPE_DEFAULT';
export const SET_STORESECTION_DEFAULT = 'SET_STORESECTION_DEFAULT';
export const SET_STORELIST_CHECKED = 'SET_STORELIST_CHECKED';
export const GROCERY_ADDLIST_OVERRIDE_ITEM = 'GROCERY_ADDLIST_OVERRIDE_ITEM';
export const WIPE_GROCERY = 'WIPE_GROCERY';

export const ADD_GROCERY = 'ADD_GROCERY';
export const DELETE_GROCERY = 'DELETE_GROCERY';
export const UPDATE_GROCERY_CHECK = 'UPDATE_GROCERY_CHECK';
export const GROCERY_ADDLIST_SET_ALL_VISIBLE = 'GROCERY_ADDLIST_SET_ALL_VISIBLE';

// store.js
export const SET_STORES = 'SET_STORES';
