# Generated by Django 2.1.3 on 2018-11-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_direction_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
            preserve_default=False,
        ),
    ]
