# Generated by Django 2.1.3 on 2018-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20181118_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='text',
            field=models.TextField(),
        ),
    ]
