# Generated by Django 2.1.3 on 2018-11-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20181124_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='recipe.Recipe'),
        ),
    ]
