# Generated by Django 2.1.3 on 2018-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20181126_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
