export const STORE_UPDATE_SECTION_ORDER = 'STORE_UPDATE_SECTION_ORDER';

export const EDIT_STORE = 'EDIT_STORE';
export const ADD_STORE = 'ADD_STORE';
export const REMOVE_STORE = 'REMOVE_STORE';

export const ADD_STORE_SECTION = 'ADD_STORE_SECTION';
export const EDIT_STORE_SECTION = 'EDIT_STORE_SECTION';
export const REMOVE_STORE_SECTION = 'REMOVE_STORE_SECTION';
