export const RECIPE_PARSE_INGREDIENTS = 'RECIPE_PARSE_INGREDIENTS';
export const RECIPE_RESET_INGREDIENTS = 'RECIPE_RESET_INGREDIENTS';
export const RECIPE_CHANGE_INGREDIENT_MATCH = 'RECIPE_CHANGE_INGREDIENT_MATCH';

export const RECIPE_PICK_POSSIBLE_INGREDIENTS = 'PICK_POSSIBLE_INGREDIENTS';
export const RECIPE_RESET_POSSIBLE_INGREDIENTS = 'RESET_POSSIBLE_INGREDIENTS';
export const RECIPE_ADHOC_INGREDIENT_MATCH = 'RECIPE_ADHOC_INGREDIENT_MATCH';

export const RECIPE_GET_SECTIONS = 'RECIPE_GET_SECTIONS';
export const RECIPE_CHANGE_INGREDIENT_SECTION = 'RECIPE_CHANGE_INGREDIENT_SECTION';
export const RECIPE_CHANGE_DIRECTION_SECTION = 'RECIPE_CHANGE_DIRECTION_SECTION';

export const RECIPE_PARSE_DIRECTIONS = 'RECIPE_PARSE_DIRECTIONS';
export const RECIPE_RESET_DIRECTIONS = 'RECIPE_RESET_DIRECTIONS';

export const RECIPE_CREATE_NEW = 'RECIPE_CREATE_NEW';

export const RECIPE_GET_LIST = 'RECIPE_GET_LIST';
export const RECIPE_GET_TAGS = 'RECIPE_GET_TAGS';
export const RECIPE_DETAIL = 'RECIPE_GET_DETAIL';
export const RECIPE_RESET = 'RECIPE_RESET';

export const RECIPE_FORM_SET_FIELD = 'RECIPE_FORM_SET_FIELD';
export const RECIPE_FORM_RESET_FIELD = 'RECIPE_FORM_RESET_FIELD';
export const RECIPE_FORM_EDIT_RECIPE = 'RECIPE_FORM_SET_ALL_FIELDS';
export const RECIPE_FORM_RESET = 'RECIPE_FORM_RESET';

export const RECIPE_FORM_ENABLE_ADD_MODE = 'RECIPE_FORM_ENABLE_ADD_MODE';
export const RECIPE_FORM_DISABLE_ADD_MODE = 'RECIPE_FORM_DISABLE_ADD_MODE';


