export const RECIPE_PARSE_INGREDIENTS = 'RECIPE_PARSE_INGREDIENTS';
export const RECIPE_RESET_INGREDIENTS = 'RECIPE_RESET_INGREDIENTS';
export const RECIPE_CHANGE_INGREDIENT_MATCH = 'RECIPE_CHANGE_INGREDIENT_MATCH';
