export const RECIPE_PARSE_INGREDIENTS = 'RECIPE_PARSE_INGREDIENTS';
export const RECIPE_RESET_INGREDIENTS = 'RECIPE_RESET_INGREDIENTS';
export const RECIPE_CHANGE_INGREDIENT_MATCH = 'RECIPE_CHANGE_INGREDIENT_MATCH';

export const RECIPE_PICK_POSSIBLE_INGREDIENTS = 'PICK_POSSIBLE_INGREDIENTS';
export const RECIPE_RESET_POSSIBLE_INGREDIENTS = 'RESET_POSSIBLE_INGREDIENTS';
export const RECIPE_ADHOC_INGREDIENT_MATCH = 'RECIPE_ADHOC_INGREDIENT_MATCH';

export const RECIPE_GET_SECTIONS = 'RECIPE_GET_SECTIONS';
export const RECIPE_CHANGE_INGREDIENT_SECTION = 'RECIPE_CHANGE_INGREDIENT_SECTION';
export const RECIPE_CHANGE_DIRECTION_SECTION = 'RECIPE_CHANGE_DIRECTION_SECTION';

export const RECIPE_PARSE_DIRECTIONS = 'RECIPE_PARSE_DIRECTIONS';
export const RECIPE_RESET_DIRECTIONS = 'RECIPE_RESET_DIRECTIONS';

export const RECIPE_CREATE_NEW = 'RECIPE_CREATE_NEW';

