export const FOOD_ADD_ITEM = 'FOOD_ADD_ITEM';
export const FOOD_UPDATE_ITEM = 'FOOD_UPDATE_ITEM';
export const SET_FOODTYPES = 'SET_FOODTYPES';
export const UPDATE_FOODTYPE_SECTION_DEFAULTS = 'UPDATE_FOODTYPE_SECTION_DEFAULTS';
export const GET_FOOD_LIST = 'GET_FOOD_LIST';
export const MODIFY_FOOD_ATTRIBUTE = 'MODIFY_FOOD_ATTRIBUTE';
export const DELETE_FOOD_ITEMS = 'DELETE_FOOD_ITEMS';